# Generated by Django 5.0.9 on 2024-10-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(db_collation='Ukrainian_CI_AS', max_length=100)),
                ('street', models.CharField(blank=True, db_collation='Ukrainian_CI_AS', max_length=255, null=True)),
                ('building', models.CharField(blank=True, db_collation='Ukrainian_CI_AS', max_length=10, null=True)),
                ('country', models.CharField(db_collation='Ukrainian_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Ukrainian_CI_AS', max_length=255)),
                ('genre', models.CharField(blank=True, db_collation='Ukrainian_CI_AS', max_length=100, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, db_collation='Ukrainian_CI_AS', null=True)),
                ('date_time', models.DateTimeField()),
                ('picture', models.CharField(blank=True, db_collation='Ukrainian_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Performance',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_collation='Ukrainian_CI_AS', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, db_collation='Ukrainian_CI_AS', max_length=100, null=True)),
                ('email', models.CharField(db_collation='Ukrainian_CI_AS', max_length=255, unique=True)),
                ('password', models.CharField(db_collation='Ukrainian_CI_AS', max_length=255)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theaters.performance')),
            ],
            options={
                'db_table': 'Seat',
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('theater_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Ukrainian_CI_AS', max_length=255)),
                ('phone_number', models.CharField(blank=True, db_collation='Ukrainian_CI_AS', max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_collation='Ukrainian_CI_AS', max_length=255, null=True)),
                ('website', models.CharField(blank=True, db_collation='Ukrainian_CI_AS', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_collation='Ukrainian_CI_AS', null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theaters.address')),
            ],
            options={
                'db_table': 'Theater',
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theaters.theater'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(blank=True, db_collation='Ukrainian_CI_AS', max_length=50, null=True)),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theaters.seat')),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, db_collation='Ukrainian_CI_AS', null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theaters.performance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theaters.user')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
