# Generated by Django 4.2.5 on 2024-10-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0003_remove_performance_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='performance',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
